services:
  - type: web
    name: cardio-risk-shap
    env: python
    pythonVersion: 3.10.11
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py --server.port=$PORT --server.address=0.0.0.0"
